-- Update WiBA requirements with BSI mapping data
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.8 Häuslicher Arbeitsplatz","INF.9 Mobiler Arbeitsplatz","SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"INF.8.A2","INF.9.A2","SYS.4.5.A5"}' WHERE id = 1;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.8 Häuslicher Arbeitsplatz"}', bsi_anforderungen = '{"INF.8.A2"}' WHERE id = 2;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.11 Allgemeines Fahrzeug","INF.9 Mobiler Arbeitsplatz"}', bsi_anforderungen = '{"INF.11.A3","INF.9.A2"}' WHERE id = 3;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.9 Mobiler Arbeitsplatz"}', bsi_anforderungen = '{"INF.9.A1"}' WHERE id = 4;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.8 Häuslicher Arbeitsplatz"}', bsi_anforderungen = '{"INF.8.A1"}' WHERE id = 5;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.11 Allgemeines Fahrzeug"}', bsi_anforderungen = '{"INF.11.A3"}' WHERE id = 6;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.9 Mobiler Arbeitsplatz"}', bsi_anforderungen = '{"INF.9.A4"}' WHERE id = 7;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.8 Häuslicher Arbeitsplatz","INF.9 Mobiler Arbeitsplatz","SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"INF.8.A5","INF.9.A6","SYS.4.1.A22"}' WHERE id = 8;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.11 Allgemeines Fahrzeug"}', bsi_anforderungen = '{"INF.11.A10","INF.11.A2"}' WHERE id = 9;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.11 Allgemeines Fahrzeug"}', bsi_anforderungen = '{"INF.11.A3"}' WHERE id = 10;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.7 Büroarbeitsplatz"}', bsi_anforderungen = '{"INF.7.A1"}' WHERE id = 11;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.1 Allgemeines Gebäude"}', bsi_anforderungen = '{"INF.1.A9"}' WHERE id = 12;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.10 Besprechungs-, Veranstaltungs- und Schulungsräume"}', bsi_anforderungen = '{"INF.10.A1"}' WHERE id = 13;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.1 Allgemeines Gebäude","INF.10 Besprechungs-, Veranstaltungs- und Schulungsräume","INF.7 Büroarbeitsplatz"}', bsi_anforderungen = '{"INF.1.A6","INF.10.A3","INF.7.A2"}' WHERE id = 14;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.1 Allgemeines Gebäude","INF.7 Büroarbeitsplatz"}', bsi_anforderungen = '{"INF.1.A6","INF.7.A2"}' WHERE id = 15;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.1 Allgemeines Gebäude"}', bsi_anforderungen = '{"INF.1.A3"}' WHERE id = 17;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A1"}' WHERE id = 18;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A2"}' WHERE id = 19;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A2"}' WHERE id = 20;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A1","CON.3.A4"}' WHERE id = 21;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A4"}' WHERE id = 22;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A2"}' WHERE id = 23;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.3 Datensicherungskonzept"}', bsi_anforderungen = '{"CON.3.A15"}' WHERE id = 24;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.6 Allgemeine Software"}', bsi_anforderungen = '{"APP.6.A1"}' WHERE id = 25;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.6 Allgemeine Software"}', bsi_anforderungen = '{"APP.6.A3"}' WHERE id = 26;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.6 Allgemeine Software"}', bsi_anforderungen = '{"APP.6.A4"}' WHERE id = 27;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.6 Allgemeine Software"}', bsi_anforderungen = '{"APP.6.A4"}' WHERE id = 28;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A2"}' WHERE id = 29;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A3"}' WHERE id = 30;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A3"}' WHERE id = 31;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A12"}' WHERE id = 32;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A12"}' WHERE id = 33;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.1 Office-Produkte"}', bsi_anforderungen = '{"APP.1.1.A13"}' WHERE id = 34;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.2 Webbrowser"}', bsi_anforderungen = '{"APP.1.2.A2"}' WHERE id = 36;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.2 Webbrowser"}', bsi_anforderungen = '{"APP.1.2.A3"}' WHERE id = 37;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.2 Webbrowser"}', bsi_anforderungen = '{"APP.1.2.A6"}' WHERE id = 38;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.1.2 Webbrowser"}', bsi_anforderungen = '{"APP.1.2.A13"}' WHERE id = 39;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A1"}' WHERE id = 40;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A1"}' WHERE id = 41;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A1"}' WHERE id = 42;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A1"}' WHERE id = 43;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A1"}' WHERE id = 44;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A1"}' WHERE id = 45;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A1"}' WHERE id = 46;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client","SYS.2.5 Client-Virtualisierung"}', bsi_anforderungen = '{"SYS.2.1.A6","SYS.2.5.A3"}' WHERE id = 47;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A8"}' WHERE id = 48;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A16","SYS.2.1.A8"}' WHERE id = 49;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A16","SYS.2.1.A42"}' WHERE id = 50;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.6 Allgemeine Software"}', bsi_anforderungen = '{"APP.6.A3"}' WHERE id = 51;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client","SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"SYS.2.1.A24","SYS.4.5.A1"}' WHERE id = 52;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A24"}' WHERE id = 53;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A27"}' WHERE id = 54;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A27"}' WHERE id = 55;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client","SYS.3.1 Laptops"}', bsi_anforderungen = '{"SYS.2.1.A28","SYS.3.1.A13"}' WHERE id = 56;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A1"}' WHERE id = 57;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A1","SYS.4.1.A2"}' WHERE id = 58;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A14"}' WHERE id = 59;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A2"}' WHERE id = 60;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A22"}' WHERE id = 61;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.1 Drucker, Kopierer und Multifunktionsgeräte"}', bsi_anforderungen = '{"SYS.4.1.A18"}' WHERE id = 62;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.1 Allgemeiner IT-Betrieb"}', bsi_anforderungen = '{"OPS.1.1.1.A4"}' WHERE id = 63;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration"}', bsi_anforderungen = '{"OPS.1.1.2.A4"}' WHERE id = 65;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.1 Allgemeiner IT-Betrieb","OPS.1.1.2 Ordnungsgemäße IT-Administration"}', bsi_anforderungen = '{"OPS.1.1.1.A2","OPS.1.1.2.A5"}' WHERE id = 66;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration"}', bsi_anforderungen = '{"OPS.1.1.2.A6"}' WHERE id = 67;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration"}', bsi_anforderungen = '{"OPS.1.1.2.A6"}' WHERE id = 68;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration"}', bsi_anforderungen = '{"OPS.1.1.2.A22"}' WHERE id = 69;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.1 Allgemeiner IT-Betrieb"}', bsi_anforderungen = '{"OPS.1.1.1.A1"}' WHERE id = 70;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.1 Detektion von sicherheitsrelevanten Ereignissen"}', bsi_anforderungen = '{"DER.1.A12"}' WHERE id = 71;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement"}', bsi_anforderungen = '{"OPS.1.1.3.A1"}' WHERE id = 72;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement","SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"OPS.1.1.3.A3","SYS.2.1.A3"}' WHERE id = 73;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement"}', bsi_anforderungen = '{"OPS.1.1.3.A15"}' WHERE id = 74;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement"}', bsi_anforderungen = '{"OPS.1.1.3.A1"}' WHERE id = 75;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement"}', bsi_anforderungen = '{"OPS.1.1.3.A1"}' WHERE id = 76;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.3 Patch- und Änderungsmanagement"}', bsi_anforderungen = '{"OPS.1.1.3.A15"}' WHERE id = 77;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A1"}' WHERE id = 78;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung","SYS.2.2.3 Clients unter Windows"}', bsi_anforderungen = '{"OPS.1.2.5.A2","SYS.2.2.3.A18"}' WHERE id = 79;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A3"}' WHERE id = 80;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A3"}' WHERE id = 81;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A3"}' WHERE id = 82;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A3","OPS.1.2.5.A8"}' WHERE id = 83;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.2.5 Fernwartung"}', bsi_anforderungen = '{"OPS.1.2.5.A5"}' WHERE id = 84;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.1 Laptops","SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.1.A1","SYS.3.2.1.A1"}' WHERE id = 85;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.3 Mobiltelefon"}', bsi_anforderungen = '{"SYS.3.3.A2"}' WHERE id = 86;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.9 Mobiler Arbeitsplatz","SYS.3.1 Laptops","SYS.3.3 Mobiltelefon","SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"INF.9.A5","SYS.3.1.A12","SYS.3.3.A3","SYS.4.5.A2"}' WHERE id = 87;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.3 Mobiltelefon"}', bsi_anforderungen = '{"SYS.3.3.A2"}' WHERE id = 88;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.9 Mobiler Arbeitsplatz","OPS.1.2.4 Telearbeit","SYS.3.1 Laptops","SYS.3.3 Mobiltelefon"}', bsi_anforderungen = '{"INF.9.A2","OPS.1.2.4.A5","SYS.3.1.A6","SYS.3.3.A3"}' WHERE id = 89;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.3 Mobiltelefon"}', bsi_anforderungen = '{"SYS.3.3.A3"}' WHERE id = 90;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.1 Laptops"}', bsi_anforderungen = '{"SYS.3.1.A3"}' WHERE id = 91;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A3"}' WHERE id = 92;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A4"}' WHERE id = 93;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A4"}' WHERE id = 94;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A4"}' WHERE id = 95;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A5"}' WHERE id = 96;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A6"}' WHERE id = 97;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A6"}' WHERE id = 98;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.3.2.1 Allgemeine Smartphones und Tablets"}', bsi_anforderungen = '{"SYS.3.2.1.A8"}' WHERE id = 99;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"SYS.4.5.A4"}' WHERE id = 100;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"SYS.4.5.A10"}' WHERE id = 101;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.4.5 Wechseldatenträger"}', bsi_anforderungen = '{"SYS.4.5.A12"}' WHERE id = 102;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A2"}' WHERE id = 103;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A2"}' WHERE id = 104;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A9"}' WHERE id = 105;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A4","NET.1.1.A8"}' WHERE id = 106;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A4"}' WHERE id = 107;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A5"}' WHERE id = 108;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A10"}' WHERE id = 109;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A8"}' WHERE id = 110;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.10 Besprechungs-, Veranstaltungs- und Schulungsräume","NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"INF.10.A6","NET.1.1.A5"}' WHERE id = 111;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.2 Netzmanagement"}', bsi_anforderungen = '{"NET.1.2.A9"}' WHERE id = 112;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A21"}' WHERE id = 113;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.2 Netzmanagement"}', bsi_anforderungen = '{"NET.1.2.A7"}' WHERE id = 114;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.2 Netzmanagement","NET.3.2 Firewall","SYS.1.5 Virtualisierung"}', bsi_anforderungen = '{"NET.1.2.A8","NET.3.2.A22","SYS.1.5.A7"}' WHERE id = 115;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.1 WLAN-Betrieb","NET.2.2 WLAN-Nutzung"}', bsi_anforderungen = '{"NET.2.1.A1","NET.2.2.A1"}' WHERE id = 116;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.2 WLAN-Nutzung"}', bsi_anforderungen = '{"NET.2.2.A1"}' WHERE id = 117;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.2 WLAN-Nutzung"}', bsi_anforderungen = '{"NET.2.2.A2"}' WHERE id = 118;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.2 WLAN-Nutzung"}', bsi_anforderungen = '{"NET.2.2.A3"}' WHERE id = 119;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.1 WLAN-Betrieb"}', bsi_anforderungen = '{"NET.2.1.A2","NET.2.1.A3"}' WHERE id = 120;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.1 WLAN-Betrieb"}', bsi_anforderungen = '{"NET.2.1.A4"}' WHERE id = 121;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.2.1 WLAN-Betrieb"}', bsi_anforderungen = '{"NET.2.1.A5"}' WHERE id = 122;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.3.1 Router und Switches"}', bsi_anforderungen = '{"NET.3.1.A4"}' WHERE id = 123;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.3.1 Router und Switches"}', bsi_anforderungen = '{"NET.3.1.A1"}' WHERE id = 124;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.3.1 Router und Switches"}', bsi_anforderungen = '{"NET.3.1.A1"}' WHERE id = 125;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design"}', bsi_anforderungen = '{"NET.1.1.A8"}' WHERE id = 126;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.1.1 Netzarchitektur und -design","NET.3.3 VPN","SYS.3.1 Laptops"}', bsi_anforderungen = '{"NET.1.1.A11","NET.3.3.A7","SYS.3.1.A9"}' WHERE id = 127;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.3.3 VPN"}', bsi_anforderungen = '{"NET.3.3.A7"}' WHERE id = 128;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation"}', bsi_anforderungen = '{"ORP.1.A2"}' WHERE id = 129;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation"}', bsi_anforderungen = '{"ORP.1.A2"}' WHERE id = 131;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration","ORP.1 Organisation"}', bsi_anforderungen = '{"OPS.1.1.2.A22","ORP.1.A2"}' WHERE id = 132;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A15"}' WHERE id = 133;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A3"}' WHERE id = 134;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation"}', bsi_anforderungen = '{"ORP.1.A4"}' WHERE id = 135;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation"}', bsi_anforderungen = '{"ORP.1.A15"}' WHERE id = 136;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation"}', bsi_anforderungen = '{"ORP.1.A15"}' WHERE id = 137;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A1","ORP.2.A14","ORP.2.A4"}' WHERE id = 138;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.1 Organisation","ORP.2 Personal"}', bsi_anforderungen = '{"ORP.1.A3","ORP.2.A4"}' WHERE id = 139;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A2","ORP.2.A4"}' WHERE id = 140;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A2"}' WHERE id = 141;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.3 Sensibilisierung und Schulung zur Informationssicherheit"}', bsi_anforderungen = '{"ORP.3.A1"}' WHERE id = 142;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.3 Sensibilisierung und Schulung zur Informationssicherheit"}', bsi_anforderungen = '{"ORP.3.A1"}' WHERE id = 143;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.3 Sensibilisierung und Schulung zur Informationssicherheit"}', bsi_anforderungen = '{"ORP.3.A3"}' WHERE id = 144;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.3 Sensibilisierung und Schulung zur Informationssicherheit"}', bsi_anforderungen = '{"ORP.3.A3"}' WHERE id = 145;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.2 Personal"}', bsi_anforderungen = '{"ORP.2.A14"}' WHERE id = 146;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.3 Nutzung von Outsourcing"}', bsi_anforderungen = '{"OPS.2.3.A4"}' WHERE id = 147;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.2 Cloud-Nutzung","OPS.2.3 Nutzung von Outsourcing"}', bsi_anforderungen = '{"OPS.2.2.A3","OPS.2.3.A2"}' WHERE id = 148;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.3 Nutzung von Outsourcing"}', bsi_anforderungen = '{"OPS.2.3.A14"}' WHERE id = 149;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.2 Cloud-Nutzung"}', bsi_anforderungen = '{"OPS.2.2.A2"}' WHERE id = 150;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.2 Cloud-Nutzung"}', bsi_anforderungen = '{"OPS.2.2.A4"}' WHERE id = 151;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.2.2 Cloud-Nutzung"}', bsi_anforderungen = '{"OPS.2.2.A9"}' WHERE id = 152;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A1"}' WHERE id = 153;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A1","ORP.4.A6","ORP.4.A7"}' WHERE id = 154;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A1","ORP.4.A2"}' WHERE id = 155;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.1 Allgemeiner IT-Betrieb","ORP.4 Identitäts- und Berechtigungsmanagement","SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"OPS.1.1.1.A2","ORP.4.A1","SYS.2.1.A16"}' WHERE id = 156;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.2 Ordnungsgemäße IT-Administration","ORP.4 Identitäts- und Berechtigungsmanagement","SYS.1.5 Virtualisierung"}', bsi_anforderungen = '{"OPS.1.1.2.A21","ORP.4.A2","SYS.1.5.A2"}' WHERE id = 157;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A2"}' WHERE id = 158;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A3"}' WHERE id = 159;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A5"}' WHERE id = 160;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A6","ORP.4.A7"}' WHERE id = 161;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A5","ORP.4.A6","ORP.4.A7"}' WHERE id = 162;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A5","ORP.4.A6"}' WHERE id = 163;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A5"}' WHERE id = 164;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A8"}' WHERE id = 165;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement","SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"ORP.4.A9","SYS.1.1.A2"}' WHERE id = 166;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.1 Kryptokonzept","ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"CON.1.A4","ORP.4.A23","ORP.4.A9"}' WHERE id = 167;
UPDATE wiba_requirements SET bsi_bausteine = '{"ORP.4 Identitäts- und Berechtigungsmanagement"}', bsi_anforderungen = '{"ORP.4.A23"}' WHERE id = 168;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum","INF.5 Raum sowie Schrank für technische Infrastruktur"}', bsi_anforderungen = '{"INF.2.A1","INF.5.A4"}' WHERE id = 169;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum"}', bsi_anforderungen = '{"INF.2.A2"}' WHERE id = 170;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum"}', bsi_anforderungen = '{"INF.2.A5"}' WHERE id = 172;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum","INF.5 Raum sowie Schrank für technische Infrastruktur"}', bsi_anforderungen = '{"INF.2.A6","INF.5.A3"}' WHERE id = 173;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum"}', bsi_anforderungen = '{"INF.2.A8"}' WHERE id = 174;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.2 Rechenzentrum sowie Serverraum"}', bsi_anforderungen = '{"INF.2.A9"}' WHERE id = 175;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.5 Raum sowie Schrank für technische Infrastruktur"}', bsi_anforderungen = '{"INF.5.A7"}' WHERE id = 176;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.6 Datenträgerarchiv"}', bsi_anforderungen = '{"INF.6.A1"}' WHERE id = 177;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.6 Datenträgerarchiv"}', bsi_anforderungen = '{"INF.6.A2"}' WHERE id = 178;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.6 Datenträgerarchiv"}', bsi_anforderungen = '{"INF.6.A3"}' WHERE id = 179;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"SYS.1.1.A1"}' WHERE id = 180;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"SYS.1.1.A1"}' WHERE id = 181;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.3 Fileserver","SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"APP.3.3.A15","SYS.1.1.A1"}' WHERE id = 182;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"SYS.1.1.A6"}' WHERE id = 183;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"SYS.1.1.A15"}' WHERE id = 184;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.5 Virtualisierung"}', bsi_anforderungen = '{"SYS.1.5.A2"}' WHERE id = 185;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.5 Virtualisierung"}', bsi_anforderungen = '{"SYS.1.5.A3"}' WHERE id = 186;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.5 Virtualisierung"}', bsi_anforderungen = '{"SYS.1.5.A12"}' WHERE id = 187;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A2"}' WHERE id = 188;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A2"}' WHERE id = 189;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A2"}' WHERE id = 190;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A2"}' WHERE id = 191;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A2"}' WHERE id = 192;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A4"}' WHERE id = 193;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A4"}' WHERE id = 194;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.3 Fileserver"}', bsi_anforderungen = '{"APP.3.3.A3"}' WHERE id = 195;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.3 Fileserver"}', bsi_anforderungen = '{"APP.3.3.A15"}' WHERE id = 196;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.3 Fileserver"}', bsi_anforderungen = '{"APP.3.3.A8"}' WHERE id = 197;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.2.1 Allgemeiner Verzeichnisdienst"}', bsi_anforderungen = '{"APP.2.1.A5"}' WHERE id = 198;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.2.2 Active Directory Domain Services"}', bsi_anforderungen = '{"APP.2.2.A6"}' WHERE id = 199;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.2.2 Active Directory Domain Services"}', bsi_anforderungen = '{"APP.2.2.A5"}' WHERE id = 200;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.2.2 Active Directory Domain Services"}', bsi_anforderungen = '{"APP.2.2.A16"}' WHERE id = 201;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.2.3 Windows Server"}', bsi_anforderungen = '{"SYS.1.2.3.A1"}' WHERE id = 202;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.2.3 Windows Server"}', bsi_anforderungen = '{"SYS.1.2.3.A2"}' WHERE id = 203;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.2.3 Windows Server"}', bsi_anforderungen = '{"SYS.1.2.3.A4"}' WHERE id = 204;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.9 Terminal-Server"}', bsi_anforderungen = '{"SYS.1.9.A4"}' WHERE id = 205;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.9 Terminal-Server"}', bsi_anforderungen = '{"SYS.1.9.A7"}' WHERE id = 206;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.1.9 Terminal-Server"}', bsi_anforderungen = '{"SYS.1.9.A12"}' WHERE id = 207;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A8"}' WHERE id = 208;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A2"}' WHERE id = 209;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A4"}' WHERE id = 210;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A3"}' WHERE id = 211;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A3"}' WHERE id = 212;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A4"}' WHERE id = 213;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.6 DNS-Server"}', bsi_anforderungen = '{"APP.3.6.A6"}' WHERE id = 214;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.4 Schutz vor Schadprogrammen"}', bsi_anforderungen = '{"OPS.1.1.4.A3"}' WHERE id = 215;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.4 Schutz vor Schadprogrammen"}', bsi_anforderungen = '{"OPS.1.1.4.A5"}' WHERE id = 216;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.5.3 Allgemeiner E-Mail-Client und -Server"}', bsi_anforderungen = '{"APP.5.3.A1"}' WHERE id = 217;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.4 Schutz vor Schadprogrammen"}', bsi_anforderungen = '{"OPS.1.1.4.A6"}' WHERE id = 218;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.4 Schutz vor Schadprogrammen"}', bsi_anforderungen = '{"OPS.1.1.4.A3"}' WHERE id = 219;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.4 Schutz vor Schadprogrammen"}', bsi_anforderungen = '{"OPS.1.1.4.A2"}' WHERE id = 220;
UPDATE wiba_requirements SET bsi_bausteine = '{"SYS.2.1 Allgemeiner Client"}', bsi_anforderungen = '{"SYS.2.1.A6"}' WHERE id = 221;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.4.1 TK-Anlagen","OPS.1.1.5 Protokollierung","SYS.1.1 Allgemeiner Server"}', bsi_anforderungen = '{"NET.4.1.A5","OPS.1.1.5.A3","SYS.1.1.A10"}' WHERE id = 222;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.5 Protokollierung"}', bsi_anforderungen = '{"OPS.1.1.5.A4"}' WHERE id = 223;
UPDATE wiba_requirements SET bsi_bausteine = '{"OPS.1.1.5 Protokollierung"}', bsi_anforderungen = '{"OPS.1.1.5.A5"}' WHERE id = 224;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.4.1 TK-Anlagen"}', bsi_anforderungen = '{"NET.4.1.A18"}' WHERE id = 225;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.4.1 TK-Anlagen"}', bsi_anforderungen = '{"NET.4.1.A8"}' WHERE id = 226;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.4.3 Faxgeräte und Faxserver"}', bsi_anforderungen = '{"NET.4.3.A1"}' WHERE id = 227;
UPDATE wiba_requirements SET bsi_bausteine = '{"NET.4.3 Faxgeräte und Faxserver"}', bsi_anforderungen = '{"NET.4.3.A2"}' WHERE id = 228;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.9 Informationsaustausch"}', bsi_anforderungen = '{"CON.9.A2"}' WHERE id = 229;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.9 Informationsaustausch"}', bsi_anforderungen = '{"CON.9.A1"}' WHERE id = 230;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.6 Löschen und Vernichten"}', bsi_anforderungen = '{"CON.6.A1"}' WHERE id = 231;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.6 Löschen und Vernichten"}', bsi_anforderungen = '{"CON.6.A2"}' WHERE id = 232;
UPDATE wiba_requirements SET bsi_bausteine = '{"CON.6 Löschen und Vernichten"}', bsi_anforderungen = '{"CON.6.A2"}' WHERE id = 233;
UPDATE wiba_requirements SET bsi_bausteine = '{"INF.9 Mobiler Arbeitsplatz"}', bsi_anforderungen = '{"INF.9.A5"}' WHERE id = 234;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A1"}' WHERE id = 235;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A2"}' WHERE id = 236;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A3"}' WHERE id = 237;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A3"}' WHERE id = 238;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A3"}' WHERE id = 239;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A5"}' WHERE id = 240;
UPDATE wiba_requirements SET bsi_bausteine = '{"DER.2.1 Behandlung von Sicherheitsvorfällen"}', bsi_anforderungen = '{"DER.2.1.A5"}' WHERE id = 241;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A1"}' WHERE id = 243;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A1"}' WHERE id = 244;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A2"}' WHERE id = 245;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A2"}' WHERE id = 246;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A2"}' WHERE id = 247;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A2"}' WHERE id = 248;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A3"}' WHERE id = 249;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A4"}' WHERE id = 250;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A5"}' WHERE id = 251;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.2 Webserver"}', bsi_anforderungen = '{"APP.3.2.A11"}' WHERE id = 252;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.1 Webanwendungen und Webservices"}', bsi_anforderungen = '{"APP.3.1.A1"}' WHERE id = 253;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.1 Webanwendungen und Webservices"}', bsi_anforderungen = '{"APP.3.1.A1"}' WHERE id = 254;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.1 Webanwendungen und Webservices"}', bsi_anforderungen = '{"APP.3.1.A4"}' WHERE id = 255;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.1 Webanwendungen und Webservices"}', bsi_anforderungen = '{"APP.3.1.A14"}' WHERE id = 256;
UPDATE wiba_requirements SET bsi_bausteine = '{"APP.3.1 Webanwendungen und Webservices"}', bsi_anforderungen = '{"APP.3.1.A14"}' WHERE id = 257;