import type { ApiService } from '../types'

export const cockpitService: ApiService = {
  name: 'Cockpit',
  slug: 'cockpit',
  description: 'IT-Systeme, Zugangsdaten und Infrastruktur-Statistiken verwalten.',
  basePath: '/api/v1/cockpit',
  auth: 'session',
  endpoints: [
    {
      method: 'GET',
      path: '/api/v1/cockpit',
      summary: 'Alle Systeme auflisten',
      description: 'Gibt paginierte IT-Systeme zurueck. Filterbar nach Kategorie, Status und Suchbegriff.',
      params: [
        { name: 'page', in: 'query', required: false, type: 'number', description: 'Seitennummer (Standard: 1)', example: '1' },
        { name: 'limit', in: 'query', required: false, type: 'number', description: 'Eintraege pro Seite (Standard: 25)', example: '25' },
        { name: 'category', in: 'query', required: false, type: 'string', description: 'Kategorie filtern (z.B. server, network, cloud, software)', example: 'server' },
        { name: 'status', in: 'query', required: false, type: 'string', description: 'Status filtern (z.B. active, maintenance, decommissioned)', example: 'active' },
        { name: 'search', in: 'query', required: false, type: 'string', description: 'Volltextsuche in Name und Beschreibung', example: 'Proxmox' },
      ],
      response: {
        items: [{ id: 'uuid', name: 'Proxmox Cluster HV01', category: 'server', status: 'active', description: 'Hauptvirtualisierung Rechenzentrum Muenchen' }],
        meta: { page: 1, limit: 25, total: 18 },
      },
      curl: `curl -s "https://example.com/api/v1/cockpit?category=server&status=active" -b cookies.txt`,
    },
    {
      method: 'POST',
      path: '/api/v1/cockpit',
      summary: 'Neues System anlegen',
      description: 'Erstellt ein neues IT-System im Cockpit. Validierung ueber Zod-Schema.',
      requestBody: {
        name: 'pfSense Firewall Hauptstandort',
        category: 'network',
        status: 'active',
        description: 'Hauptfirewall mit VPN-Gateway fuer alle Standorte',
        url: 'https://fw01.intern.musterit.de',
        ipAddress: '10.0.0.1',
        location: 'Serverraum Muenchen',
        vendor: 'Netgate',
        model: 'SG-5100',
        serialNumber: 'NG-5100-2024-DE-0042',
        purchaseDate: '2024-06-15',
        warrantyEnd: '2027-06-15',
        notes: 'Firmware-Update quartalsweise geplant',
      },
      response: { id: 'uuid', name: 'pfSense Firewall Hauptstandort', category: 'network', status: 'active' },
      curl: `curl -s -X POST https://example.com/api/v1/cockpit -b cookies.txt -H "Content-Type: application/json" -d '{"name":"pfSense Firewall Hauptstandort","category":"network","status":"active","description":"Hauptfirewall mit VPN-Gateway","url":"https://fw01.intern.musterit.de","ipAddress":"10.0.0.1","location":"Serverraum Muenchen","vendor":"Netgate"}'`,
    },
    {
      method: 'GET',
      path: '/api/v1/cockpit/{id}',
      summary: 'Einzelnes System abrufen',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)', example: 'd4e5f6a7-b8c9-0123-defg-456789abcdef' },
      ],
      response: { id: 'uuid', name: 'Proxmox Cluster HV01', category: 'server', status: 'active', ipAddress: '10.0.1.10' },
      curl: `curl -s https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt`,
    },
    {
      method: 'PUT',
      path: '/api/v1/cockpit/{id}',
      summary: 'System aktualisieren',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
      ],
      requestBody: {
        name: 'Proxmox Cluster HV01 (erweitert)',
        status: 'active',
        notes: 'RAM-Upgrade auf 256 GB durchgefuehrt am 2026-03-20',
      },
      response: { id: 'uuid', name: 'Proxmox Cluster HV01 (erweitert)', status: 'active' },
      curl: `curl -s -X PUT https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt -H "Content-Type: application/json" -d '{"name":"Proxmox Cluster HV01 (erweitert)","notes":"RAM-Upgrade auf 256 GB durchgefuehrt am 2026-03-20"}'`,
    },
    {
      method: 'DELETE',
      path: '/api/v1/cockpit/{id}',
      summary: 'System loeschen',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
      ],
      response: { message: 'System deleted successfully' },
      curl: `curl -s -X DELETE https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt`,
    },
    {
      method: 'GET',
      path: '/api/v1/cockpit/{id}/credentials',
      summary: 'Zugangsdaten eines Systems auflisten',
      description: 'Gibt alle Zugangsdaten (Credentials) fuer ein bestimmtes System zurueck.',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
      ],
      response: { items: [{ id: 'uuid', label: 'root SSH', username: 'root', url: 'ssh://10.0.1.10:22' }] },
      curl: `curl -s https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef/credentials -b cookies.txt`,
    },
    {
      method: 'POST',
      path: '/api/v1/cockpit/{id}/credentials',
      summary: 'Zugangsdaten hinzufuegen',
      description: 'Erstellt neue Zugangsdaten fuer ein System. Validierung ueber Zod-Schema.',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
      ],
      requestBody: {
        label: 'Admin Web-UI',
        username: 'admin',
        password: 'sicheres-passwort-hier',
        url: 'https://fw01.intern.musterit.de',
        notes: 'Zwei-Faktor-Authentifizierung aktiviert',
      },
      response: { id: 'uuid', label: 'Admin Web-UI', username: 'admin' },
      curl: `curl -s -X POST https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef/credentials -b cookies.txt -H "Content-Type: application/json" -d '{"label":"Admin Web-UI","username":"admin","password":"sicheres-passwort-hier","url":"https://fw01.intern.musterit.de","notes":"Zwei-Faktor-Authentifizierung aktiviert"}'`,
    },
    {
      method: 'PUT',
      path: '/api/v1/cockpit/{id}/credentials/{credentialId}',
      summary: 'Zugangsdaten aktualisieren',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
        { name: 'credentialId', in: 'path', required: true, type: 'string', description: 'Credential-ID (UUID)', example: 'e5f6a7b8-c9d0-1234-efgh-567890abcdef' },
      ],
      requestBody: {
        label: 'Admin Web-UI (aktualisiert)',
        password: 'neues-sicheres-passwort',
        notes: '2FA mit TOTP, Backup-Codes im Tresor',
      },
      response: { id: 'uuid', label: 'Admin Web-UI (aktualisiert)' },
      curl: `curl -s -X PUT https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef/credentials/e5f6a7b8-c9d0-1234-efgh-567890abcdef -b cookies.txt -H "Content-Type: application/json" -d '{"label":"Admin Web-UI (aktualisiert)","password":"neues-sicheres-passwort"}'`,
    },
    {
      method: 'DELETE',
      path: '/api/v1/cockpit/{id}/credentials/{credentialId}',
      summary: 'Zugangsdaten loeschen',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'System-ID (UUID)' },
        { name: 'credentialId', in: 'path', required: true, type: 'string', description: 'Credential-ID (UUID)' },
      ],
      response: { message: 'Credential deleted successfully' },
      curl: `curl -s -X DELETE https://example.com/api/v1/cockpit/d4e5f6a7-b8c9-0123-defg-456789abcdef/credentials/e5f6a7b8-c9d0-1234-efgh-567890abcdef -b cookies.txt`,
    },
    {
      method: 'GET',
      path: '/api/v1/cockpit/stats',
      summary: 'Cockpit-Statistiken abrufen',
      description: 'Gibt aggregierte Statistiken ueber alle IT-Systeme des Mandanten zurueck (Anzahl, Status-Verteilung, Kategorien).',
      response: { totalSystems: 18, byStatus: { active: 14, maintenance: 3, decommissioned: 1 }, byCategory: { server: 5, network: 4, cloud: 6, software: 3 } },
      curl: `curl -s https://example.com/api/v1/cockpit/stats -b cookies.txt`,
    },
  ],
}
