import type { ApiService } from '../types'

export const timeEntriesService: ApiService = {
  name: 'Zeiterfassung',
  slug: 'time-entries',
  description: 'Zeiteintraege erfassen, Timer steuern und Rechnungen aus Zeiteintraegen generieren.',
  basePath: '/api/v1/time-entries',
  auth: 'session',
  endpoints: [
    {
      method: 'GET',
      path: '/api/v1/time-entries',
      summary: 'Zeiteintraege auflisten',
      description: 'Gibt paginierte Zeiteintraege zurueck. Filterbar nach Firma und Zeitraum.',
      params: [
        { name: 'page', in: 'query', required: false, type: 'number', description: 'Seitennummer (Standard: 1)', example: '1' },
        { name: 'limit', in: 'query', required: false, type: 'number', description: 'Eintraege pro Seite (Standard: 25)', example: '25' },
        { name: 'companyId', in: 'query', required: false, type: 'string', description: 'Nach Firma filtern (UUID)' },
        { name: 'from', in: 'query', required: false, type: 'string', description: 'Startdatum (ISO 8601)', example: '2026-01-01' },
        { name: 'to', in: 'query', required: false, type: 'string', description: 'Enddatum (ISO 8601)', example: '2026-03-31' },
      ],
      response: {
        items: [{ id: 'uuid', description: 'Server-Migration Musterhaus GmbH', date: '2026-03-15', durationMinutes: 120, billable: true, hourlyRate: '120.00' }],
        meta: { page: 1, limit: 25, total: 42 },
      },
      curl: `curl -s "https://example.com/api/v1/time-entries?from=2026-01-01&to=2026-03-31&limit=10" -b cookies.txt`,
    },
    {
      method: 'POST',
      path: '/api/v1/time-entries',
      summary: 'Neuen Zeiteintrag erstellen',
      description: 'Erstellt einen manuellen Zeiteintrag. Erfordert einen angemeldeten Benutzer.',
      requestBody: {
        companyId: 'c1d2e3f4-a5b6-7890-cdef-123456789abc',
        description: 'Firewall-Konfiguration und Netzwerk-Audit',
        date: '2026-03-28',
        startTime: '2026-03-28T09:00:00Z',
        endTime: '2026-03-28T11:30:00Z',
        durationMinutes: 150,
        billable: true,
        hourlyRate: 135,
      },
      response: { id: 'uuid', description: 'Firewall-Konfiguration und Netzwerk-Audit', durationMinutes: 150 },
      curl: `curl -s -X POST https://example.com/api/v1/time-entries -b cookies.txt -H "Content-Type: application/json" -d '{"companyId":"c1d2e3f4-a5b6-7890-cdef-123456789abc","description":"Firewall-Konfiguration und Netzwerk-Audit","date":"2026-03-28","durationMinutes":150,"billable":true,"hourlyRate":135}'`,
    },
    {
      method: 'GET',
      path: '/api/v1/time-entries/{id}',
      summary: 'Einzelnen Zeiteintrag abrufen',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'Zeiteintrag-ID (UUID)' },
      ],
      response: { id: 'uuid', description: 'Server-Migration', date: '2026-03-15', durationMinutes: 120, billable: true },
      curl: `curl -s https://example.com/api/v1/time-entries/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt`,
    },
    {
      method: 'PUT',
      path: '/api/v1/time-entries/{id}',
      summary: 'Zeiteintrag aktualisieren',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'Zeiteintrag-ID (UUID)' },
      ],
      requestBody: {
        description: 'Server-Migration (Phase 2)',
        durationMinutes: 180,
        billable: true,
      },
      response: { id: 'uuid', description: 'Server-Migration (Phase 2)', durationMinutes: 180 },
      curl: `curl -s -X PUT https://example.com/api/v1/time-entries/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt -H "Content-Type: application/json" -d '{"description":"Server-Migration (Phase 2)","durationMinutes":180}'`,
    },
    {
      method: 'DELETE',
      path: '/api/v1/time-entries/{id}',
      summary: 'Zeiteintrag loeschen',
      params: [
        { name: 'id', in: 'path', required: true, type: 'string', description: 'Zeiteintrag-ID (UUID)' },
      ],
      response: { deleted: true },
      curl: `curl -s -X DELETE https://example.com/api/v1/time-entries/d4e5f6a7-b8c9-0123-defg-456789abcdef -b cookies.txt`,
    },
    {
      method: 'GET',
      path: '/api/v1/time-entries/timer',
      summary: 'Laufenden Timer abrufen',
      description: 'Gibt den aktuell laufenden Timer des angemeldeten Benutzers zurueck, oder null falls keiner laeuft.',
      response: { id: 'uuid', description: 'Support-Anfrage Muster GmbH', startTime: '2026-03-31T08:15:00Z', companyId: 'uuid' },
      curl: `curl -s https://example.com/api/v1/time-entries/timer -b cookies.txt`,
    },
    {
      method: 'POST',
      path: '/api/v1/time-entries/timer',
      summary: 'Timer starten oder stoppen',
      description: 'Startet einen neuen Timer (action: start) oder stoppt den laufenden Timer (action: stop). Beim Stoppen wird die Dauer automatisch berechnet.',
      requestBody: {
        action: 'start',
        companyId: 'c1d2e3f4-a5b6-7890-cdef-123456789abc',
        description: 'Netzwerk-Stoerung bei Schmidt & Partner',
        hourlyRate: 120,
      },
      response: { id: 'uuid', description: 'Netzwerk-Stoerung bei Schmidt & Partner', startTime: '2026-03-31T08:15:00Z' },
      curl: `curl -s -X POST https://example.com/api/v1/time-entries/timer -b cookies.txt -H "Content-Type: application/json" -d '{"action":"start","companyId":"c1d2e3f4-a5b6-7890-cdef-123456789abc","description":"Netzwerk-Stoerung bei Schmidt & Partner","hourlyRate":120}'`,
    },
    {
      method: 'POST',
      path: '/api/v1/time-entries/invoice',
      summary: 'Rechnung aus Zeiteintraegen erstellen',
      description: 'Erstellt eine Rechnung aus abrechenbaren Zeiteintraegen einer Firma. Optional kann der Zeitraum und ein Stundensatz angegeben werden. Positionen werden automatisch aus den Zeiteintraegen generiert (19% MwSt).',
      requestBody: {
        companyId: 'c1d2e3f4-a5b6-7890-cdef-123456789abc',
        from: '2026-01-01',
        to: '2026-03-31',
        hourlyRate: 120,
      },
      response: {
        invoiceId: 'uuid',
        invoiceNumber: 'RE-2026-0042',
        entriesCount: 8,
        totalMinutes: 960,
        totalHours: 16,
      },
      curl: `curl -s -X POST https://example.com/api/v1/time-entries/invoice -b cookies.txt -H "Content-Type: application/json" -d '{"companyId":"c1d2e3f4-a5b6-7890-cdef-123456789abc","from":"2026-01-01","to":"2026-03-31","hourlyRate":120}'`,
    },
  ],
}
