import type { NewDinGrant } from '../schema'

export const grantsSeedData: Omit<NewDinGrant, 'id'>[] = [
  // BUNDESWEITE PROGRAMME
  {
    name: 'go-digital',
    provider: 'Bundesministerium fuer Wirtschaft und Klimaschutz (BMWK)',
    purpose: 'Foerderung der Digitalisierung in KMU durch autorisierte Beratungsunternehmen. Bis zu 16.500 EUR (50% Foerderquote)',
    region: 'Bundesweit',
    url: 'https://www.innovation-beratung-foerderung.de/INNO/Navigation/DE/go-digital/go-digital.html',
    minEmployees: null,
    maxEmployees: 100,
  },
  {
    name: 'Digital Jetzt',
    provider: 'Bundesministerium fuer Wirtschaft und Klimaschutz (BMWK)',
    purpose: 'Investitionen in digitale Technologien und Qualifizierung. Bis zu 50.000 EUR (max. 50% Foerderquote)',
    region: 'Bundesweit',
    url: 'https://www.digital-jetzt.de/',
    minEmployees: 3,
    maxEmployees: 499,
  },
  {
    name: 'KfW-Kredit Digitalisierung',
    provider: 'Kreditanstalt fuer Wiederaufbau (KfW)',
    purpose: 'Guenstige Finanzierung fuer Digitalisierungsvorhaben und IT-Sicherheit. Bis zu 25 Mio. EUR',
    region: 'Bundesweit',
    url: 'https://www.kfw.de/inlandsfoerderung/Unternehmen/Digitalisierung/',
    minEmployees: null,
    maxEmployees: null,
  },
  // LAENDERPROGRAMME
  {
    name: 'Digital-Impuls BW',
    provider: 'Ministerium fuer Wirtschaft Baden-Wuerttemberg',
    purpose: 'Foerderung von Digitalisierungsprojekten in KMU. Bis zu 50.000 EUR (50% Foerderquote)',
    region: 'Baden-Wuerttemberg',
    url: 'https://wm.baden-wuerttemberg.de/de/innovation/foerderprogramme/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Bayern Digital',
    provider: 'Bayerisches Staatsministerium fuer Wirtschaft',
    purpose: 'Foerderung der digitalen Transformation. Bis zu 30.000 EUR (50% Foerderquote)',
    region: 'Bayern',
    url: 'https://www.stmwi.bayern.de/foerderungen/digitalbonus/',
    minEmployees: 3,
    maxEmployees: 249,
  },
  {
    name: 'Digitalbonus Bayern',
    provider: 'Bayerisches Staatsministerium fuer Wirtschaft',
    purpose: 'Investitionen in IT-Sicherheit, E-Commerce und digitale Geschäftsprozesse. Bis zu 10.000 EUR',
    region: 'Bayern',
    url: 'https://www.digitalbonus.bayern/',
    minEmployees: null,
    maxEmployees: 49,
  },
  {
    name: 'Berlin Digital Programm',
    provider: 'Investitionsbank Berlin (IBB)',
    purpose: 'Foerderung digitaler Geschäftsmodelle und IT-Infrastruktur. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Berlin',
    url: 'https://www.ibb.de/de/foerderprogramme/berlin-digital-programm.html',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Brandenburg Digital',
    provider: 'Ministerium fuer Wirtschaft Brandenburg',
    purpose: 'Unterstuetzung bei Digitalisierung und IT-Sicherheit. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Brandenburg',
    url: 'https://www.ilb.de/de/wirtschaft/zuschuesse/brandenburg-digital/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Bremen Digital',
    provider: 'Senatorin fuer Wirtschaft Bremen',
    purpose: 'Foerderung digitaler Transformationsprojekte. Bis zu 15.000 EUR (50% Foerderquote)',
    region: 'Bremen',
    url: 'https://www.bab-bremen.de/foerderung/digitalisierung/',
    minEmployees: null,
    maxEmployees: 249,
  },
  {
    name: 'Hamburg Digital',
    provider: 'Hamburgische Investitions- und Foerderbank (IFB)',
    purpose: 'Investitionen in Digitalisierung und Cybersecurity. Bis zu 25.000 EUR (50% Foerderquote)',
    region: 'Hamburg',
    url: 'https://www.ifbhh.de/foerderprogramm/hamburg-digital',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Digitalpraemie Hessen',
    provider: 'Hessisches Ministerium fuer Wirtschaft',
    purpose: 'Foerderung von Digitalisierungsmassnahmen in KMU. Bis zu 12.000 EUR (50% Foerderquote)',
    region: 'Hessen',
    url: 'https://www.wibank.de/wibank/foerderung/digitalpraemie/374650',
    minEmployees: 1,
    maxEmployees: 50,
  },
  {
    name: 'MV Digital',
    provider: 'Ministerium fuer Wirtschaft Mecklenburg-Vorpommern',
    purpose: 'Unterstuetzung digitaler Geschäftsprozesse. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Mecklenburg-Vorpommern',
    url: 'https://www.lfi-mv.de/foerderungen/digitalisierung/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Niedersachsen Digital',
    provider: 'NBank - Investitions- und Foerderbank Niedersachsen',
    purpose: 'Digitalisierung und IT-Sicherheit fuer KMU. Bis zu 30.000 EUR (50% Foerderquote)',
    region: 'Niedersachsen',
    url: 'https://www.nbank.de/Unternehmen/Digitalisierung/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Digitalbonus NRW',
    provider: 'Ministerium fuer Wirtschaft NRW',
    purpose: 'Foerderung der digitalen Transformation in KMU. Bis zu 12.000 EUR (50% Foerderquote)',
    region: 'Nordrhein-Westfalen',
    url: 'https://www.wirtschaft.nrw/digitalbonus',
    minEmployees: 3,
    maxEmployees: 499,
  },
  {
    name: 'Mittelstand Innovativ & Digital NRW',
    provider: 'Ministerium fuer Wirtschaft NRW',
    purpose: 'Innovations- und Digitalisierungsvorhaben. Bis zu 50.000 EUR (50% Foerderquote)',
    region: 'Nordrhein-Westfalen',
    url: 'https://www.wirtschaft.nrw/mid',
    minEmployees: null,
    maxEmployees: 499,
  },
  {
    name: 'Digital Durchstarten RLP',
    provider: 'Ministerium fuer Wirtschaft Rheinland-Pfalz',
    purpose: 'Unterstuetzung bei Digitalisierungsprojekten. Bis zu 15.000 EUR (50% Foerderquote)',
    region: 'Rheinland-Pfalz',
    url: 'https://mwvlw.rlp.de/de/themen/digitalisierung/foerderung/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Saarland Digital',
    provider: 'Ministerium fuer Wirtschaft Saarland',
    purpose: 'Digitalisierung und IT-Sicherheit. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Saarland',
    url: 'https://www.saarland.de/mwaev/DE/portale/digitalisierung/foerderung/foerderung_node.html',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Digitalisierungspraemie Sachsen',
    provider: 'Saechsisches Staatsministerium fuer Wirtschaft',
    purpose: 'Foerderung digitaler Technologien und Prozesse. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Sachsen',
    url: 'https://www.sab.sachsen.de/foerderprogramme/digitalisierungspraemie.jsp',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Sachsen-Anhalt Digital',
    provider: 'Investitionsbank Sachsen-Anhalt',
    purpose: 'Digitalisierung in KMU. Bis zu 25.000 EUR (50% Foerderquote)',
    region: 'Sachsen-Anhalt',
    url: 'https://www.ib-sachsen-anhalt.de/foerderung/digitalisierung/',
    minEmployees: null,
    maxEmployees: 250,
  },
  {
    name: 'Digitalisierungsbonus SH',
    provider: 'Ministerium fuer Wirtschaft Schleswig-Holstein',
    purpose: 'Foerderung von Digitalisierungsvorhaben. Bis zu 15.000 EUR (50% Foerderquote)',
    region: 'Schleswig-Holstein',
    url: 'https://www.schleswig-holstein.de/DE/Landesregierung/MWVATT/Service/Foerderprogramme/_documents/digitalisierungsbonus.html',
    minEmployees: null,
    maxEmployees: 249,
  },
  {
    name: 'Thueringen Digital',
    provider: 'Thueringer Aufbaubank',
    purpose: 'Unterstuetzung bei digitaler Transformation. Bis zu 20.000 EUR (50% Foerderquote)',
    region: 'Thueringen',
    url: 'https://www.aufbaubank.de/Foerderprogramme/Digitalisierung',
    minEmployees: null,
    maxEmployees: 250,
  },
]
