import { db } from '@/lib/db'
import { sopDocuments, deliverables } from '@/lib/db/schema'
import { eq, and, isNull } from 'drizzle-orm'
import { logger } from '@/lib/utils/logger'

const MOD = 'SopSeed'

// ============================================================
// Source: temp/xKMU_AI_Business_Framework_v2.json
// sop_module.catalog — alle Eintraege
//
// Gruppe 1: Allgemeine SOPs (ohne source_task_id, 14 Eintraege)
//   SOP-V001 bis SOP-F002
// Gruppe 2: Operative SOPs (mit source_task_id)
//   KP1: SOP-MK001..MK012 (KP1-01..KP1-12)
//   KP2: SOP-VT001..VT014 (KP2-01..KP2-14)
//   KP3: SOP-LB001..LB021 (KP3-01..KP3-21)
//   KP4: SOP-AB001..AB007 (KP4-01..KP4-07)
//   KP5: SOP-KB001..KB008 (KP5-01..KP5-08)
//   MP:  SOP-MP001..MP005 (MP-01..MP-05)
//   UP:  SOP-UP001..UP009 (UP-01..UP-09)
//   KP6 (IT-Beratung): SOP-IT004..IT009 (KP6-04..KP6-09)
//   KP7 (Cybersecurity): SOP-CS001..CS013 (KP7-01..KP7-13)
// ============================================================

// Mapping von JSON produces_deliverable Codes -> Deliverable-Namen aus dem Catalog
// Nur Codes mit bekanntem Match aus deliverable-catalog.seed.ts werden hier eingetragen.
// Unbekannte Codes -> producesDeliverableId = null + logger.warn()
const DELIVERABLE_CODE_TO_NAME: Record<string, string> = {
  // DEL-IT001 = Security Check / Audit Report -> IT-Health-Report (Modul B1)
  'DEL-IT001': 'IT-Health-Report',
  // DEL-IT003 = Abnahmeprotokoll -> Abnahmeprotokoll (digital signiert) (Modul A2)
  'DEL-IT003': 'Abnahmeprotokoll (digital signiert)',
  // DEL-P002 = Kick-off-Protokoll -> kein exakter Match; naechster: kein Pass
  // DEL-V001, DEL-V002, DEL-P001, DEL-C001 -> kein exakter Deliverable-Name im Catalog
  // Diese werden als null gesetzt + logger.warn
}

// dauer -> estimatedDurationMinutes Parsing
function parseDauer(dauer: string | undefined): number | null {
  if (!dauer) return null
  // "30 Min" -> 30, "60 Min/Monat" -> 60, "5 Min/Tag" -> 5, "15 Min/Woche" -> 15
  const minMatch = dauer.match(/^(\d+)\s*Min/)
  if (minMatch) return parseInt(minMatch[1])
  // "4-8 Std" -> (4+8)/2 * 60 = 360, "2 Std/Jahr" -> 120, "1 Std" -> 60
  const stdMatch = dauer.match(/^(\d+)(?:-(\d+))?\s*Std/)
  if (stdMatch) {
    const low = parseInt(stdMatch[1])
    const high = stdMatch[2] ? parseInt(stdMatch[2]) : low
    return Math.round(((low + high) / 2) * 60)
  }
  // "5-10 Min" -> (5+10)/2 = 7 (rounded)
  const minRangeMatch = dauer.match(/^(\d+)-(\d+)\s*Min/)
  if (minRangeMatch) {
    const low = parseInt(minRangeMatch[1])
    const high = parseInt(minRangeMatch[2])
    return Math.round((low + high) / 2)
  }
  // "Einmalig", "Variabel" -> null
  return null
}

type SopEntry = {
  sop_id: string
  source_task_id?: string
  title: string
  category: string
  subprocess?: string
  dauer?: string
  automation_level?: string
  maturity_level?: number
  output_beschreibung?: string
  produces_deliverable?: string | null
  status?: string
}

// ============================================================
// GRUPPE 1: Allgemeine SOPs (keine source_task_id)
// ============================================================
const GENERAL_SOPS: SopEntry[] = [
  {
    sop_id: 'SOP-V001',
    title: 'Neukundenakquise \u2013 Erstansprache',
    category: 'Vertrieb',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-V001',
    status: 'approved',
  },
  {
    sop_id: 'SOP-V002',
    title: 'Angebotserstellung',
    category: 'Vertrieb',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-V002',
    status: 'approved',
  },
  {
    sop_id: 'SOP-V003',
    title: 'Follow-up Sequenz',
    category: 'Vertrieb',
    automation_level: 'full',
    maturity_level: 4,
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT001',
    title: 'Incident Response',
    category: 'IT & Cybersicherheit',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-IT003',
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT002',
    title: 'Zugangsmanagement',
    category: 'IT & Cybersicherheit',
    automation_level: 'manual',
    maturity_level: 2,
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT003',
    title: 'Security Check & DIN SPEC 27076 Audit',
    category: 'IT & Cybersicherheit',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-IT001',
    status: 'draft',
  },
  {
    sop_id: 'SOP-M001',
    title: 'Blogpost-Workflow',
    category: 'Marketing',
    automation_level: 'full',
    maturity_level: 4,
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-M002',
    title: 'Social Media',
    category: 'Marketing',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: null,
    status: 'draft',
  },
  {
    sop_id: 'SOP-P001',
    title: 'Projekt-Kickoff',
    category: 'Projektmanagement',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-P002',
    status: 'approved',
  },
  {
    sop_id: 'SOP-P002',
    title: 'Projektabschluss',
    category: 'Projektmanagement',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-P001',
    status: 'draft',
  },
  {
    sop_id: 'SOP-C001',
    title: 'DSGVO-Auskunftsanfrage',
    category: 'Compliance & DSGVO',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: 'DEL-C001',
    status: 'approved',
  },
  {
    sop_id: 'SOP-C002',
    title: 'Datenpanne melden',
    category: 'Compliance & DSGVO',
    automation_level: 'manual',
    maturity_level: 2,
    produces_deliverable: null,
    status: 'draft',
  },
  {
    sop_id: 'SOP-F001',
    title: 'Rechnungsstellung',
    category: 'Finanzen',
    automation_level: 'semi',
    maturity_level: 3,
    produces_deliverable: null,
    status: 'draft',
  },
  {
    sop_id: 'SOP-F002',
    title: 'Monatsabschluss',
    category: 'Finanzen',
    automation_level: 'manual',
    maturity_level: 2,
    produces_deliverable: null,
    status: 'draft',
  },
]

// ============================================================
// GRUPPE 2: Operative SOPs (mit source_task_id)
// ============================================================
const OPERATIVE_SOPS: SopEntry[] = [
  // ── KP1: Marketing & Lead-Generierung ──────────────────────
  {
    sop_id: 'SOP-MK001',
    source_task_id: 'KP1-01',
    title: 'Themenfindung',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Keyword-recherchierte, nach Kundenproblemen priorisierte Themenliste in Trello/Notion. Basis fuer naechste 4 Wochen Content-Planung.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK002',
    source_task_id: 'KP1-02',
    title: 'Gliederung erstellen',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '15 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Strukturierte Gliederung mit H2/H3-Ebenen, manuell geprueft und angepasst. Enthalt Kernaussagen je Abschnitt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK003',
    source_task_id: 'KP1-03',
    title: 'Rohtext erstellen',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendiger Rohartikel (800-1200 Woerter), alle Gliederungspunkte ausformuliert, noch nicht SEO-optimiert und nicht personalisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK004',
    source_task_id: 'KP1-04',
    title: 'Ueberarbeitung & SEO',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '60 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Veroeffentlichungsfertiger Artikel mit eingearbeiteten Keywords, H2/H3-Struktur, Meta-Description, personalisierten Praxisbeispielen und mindestens 20% manuellem Anteil.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK005',
    source_task_id: 'KP1-05',
    title: 'Bilderstellung',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '20 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Passendes Titelbild erstellt mit Midjourney oder Canva AI, Seitenverhaeltnis 16:9, komprimiert und fuer Web optimiert. Dateiname nach Naming-Convention.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK006',
    source_task_id: 'KP1-06',
    title: 'Social-Media-Snippets',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.1 Content-Erstellung',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Plattformangepasste Posts fuer LinkedIn und XING: Intro-Hook, Kernaussage, Handlungsaufforderung, passende Hashtags. Varianten fuer unterschiedliche Wochentage.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK007',
    source_task_id: 'KP1-07',
    title: 'Blogartikel veroeffentlichen',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.2 Content-Verbreitung',
    dauer: '20 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Artikel live auf Website: SEO-Plugin ausgefuellt (Yoast/RankMath), Titelbild hinterlegt, Kategorie und Tags gesetzt, interne Verlinkungen geprueft, CTA eingebaut.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK008',
    source_task_id: 'KP1-08',
    title: 'Social Media Posts planen',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.2 Content-Verbreitung',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Alle Snippets terminiert und eingeplant: optimale Versandzeiten (Di/Do 9-11 Uhr), Bilder hochgeladen, Vorschau geprueft. Kein manueller Aufwand am Versandtag.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK009',
    source_task_id: 'KP1-09',
    title: 'Interaktion & Community',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.2 Content-Verbreitung',
    dauer: '15 Min/Tag',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Alle Kommentare und Nachrichten innerhalb 24h beantwortet. Neue relevante Kontakte angenommen und mit personalisierter Nachricht begruessen. Engagement-Rate in Notion notiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK010',
    source_task_id: 'KP1-10',
    title: 'Newsletter-Konzept',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.3 Newsletter',
    dauer: '30 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Monatliches Newsletter-Briefing: Hauptthema, 3 Content-Bloecke (Tipp, Artikel, Tool-Empfehlung), Call-to-Action, Betreffzeilen-Varianten (A/B-Test).',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK011',
    source_task_id: 'KP1-11',
    title: 'Newsletter-Erstellung',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.3 Newsletter',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendige Kampagne erstellt und geprueft: Inhalt, Bilder, Links funktionsfaehig, Vorschau auf Mobile geprueft, Abmeldelink vorhanden, Versandzeitplan gesetzt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MK012',
    source_task_id: 'KP1-12',
    title: 'Versand & Analyse',
    category: 'Marketing & Lead-Generierung',
    subprocess: '1.3 Newsletter',
    dauer: '15 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Newsletter erfolgreich versendet. 48h nach Versand: Oeffnungsrate, Klickrate, Abmeldungen und Bounces in Google Sheets eingetragen. KI-Analyse und Optimierungsvorschlag dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP2: Vertrieb & Onboarding ──────────────────────────────
  {
    sop_id: 'SOP-VT001',
    source_task_id: 'KP2-01',
    title: 'Anfrage-Eingang',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.1 Anfrage-Bearbeitung',
    dauer: '5 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Jede Anfrage sofort in HubSpot angelegt: Kontaktdaten, Kanal, Anliegen (Kategorie A/B/C), Qualifizierungsscore vorlaeufig. Automatisch via Zapier aus Webformular.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT002',
    source_task_id: 'KP2-02',
    title: 'Schnelle Qualifizierung',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.1 Anfrage-Bearbeitung',
    dauer: '5 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Bewertung nach Budget (hat der Interessent Mittel?), Authority (ist er Entscheider?), Need (konkreter Bedarf?) und Timing (wann soll es losgehen?). Ergebnis im CRM hinterlegt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT003',
    source_task_id: 'KP2-03',
    title: 'Standardisierte Erstantwort',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.1 Anfrage-Bearbeitung',
    dauer: '10 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Professionelle Antwort innerhalb von 2 Stunden: Danke fuer Anfrage, kurze Reaktion auf spezifisches Anliegen, Calendly-Link fuer Erstgespraech, kurze Vorstellung xKMU.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT004',
    source_task_id: 'KP2-04',
    title: 'CRM-Eintrag erstellen',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.1 Anfrage-Bearbeitung',
    dauer: '5 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Deal mit allen Pflichtfeldern: Kontakt, Unternehmen, Branche, Deal-Wert (Schaetzung), Stage (Anfrage), Quelle, naechste Aufgabe (Erstgespraech termin). Automatisch via Zapier.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT005',
    source_task_id: 'KP2-05',
    title: 'Gespraechsvorbereitung',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.2 Erstgespraech',
    dauer: '5 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Personalisierte Gespraechsagenda im CRM: Erkenntnisse aus CRM-Notizen, 3 branchenspezifische KI-Fragen, Calendly-Buchungsdetails, Zoom-Link getestet.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT006',
    source_task_id: 'KP2-06',
    title: 'Gespraechsdurchfuehrung',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.2 Erstgespraech',
    dauer: '30 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Otter.ai-Transkription des 30-minuetigen Gespraeches. KI-Prompt extrahiert: Hauptproblem, Wunschloesung, Budget-Indikation, naechste Schritte. Im CRM hinterlegt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT007',
    source_task_id: 'KP2-07',
    title: 'Nachbereitung & CRM-Update',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.2 Erstgespraech',
    dauer: '10 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'HubSpot-Deal aktualisiert (Stage: Erstgespraech gefuehrt, Notizen). E-Mail an Kunden: Zusammenfassung des Gespraeches, besprochene Punkte, Angebot bis [Datum] zugesagt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT008',
    source_task_id: 'KP2-08',
    title: 'Angebot erstellen',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.3 Angebot & Abschluss',
    dauer: '20 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Formelles Angebot aus Lexoffice: Leistungsbeschreibung (aus CRM-Notizen), Preis (Festpreis 490 EUR oder Stundensatz 95 EUR), Zahlungsbedingungen (Vorauszahlung oder 14 Tage), Gueltigkeit 14 Tage.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT009',
    source_task_id: 'KP2-09',
    title: 'Angebot versenden',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.3 Angebot & Abschluss',
    dauer: '5 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Angebot per E-Mail mit persoenlichem Begleittext. HubSpot-Deal automatisch auf Stage Angebot gesetzt via Zapier. Wiedervorlage nach 5 Tagen angelegt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT010',
    source_task_id: 'KP2-10',
    title: 'Follow-up nach 5 Tagen',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.3 Angebot & Abschluss',
    dauer: '5 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Maximal 3 Saetze: Bezug auf Angebot, Frage ob Rueckfragen, Terminangebot fuer kurzes Klaerungsgespraech. Kein Verkaufsdruck. Automatisch via CRM-Sequenz.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT011',
    source_task_id: 'KP2-11',
    title: 'Vertragsabschluss',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.3 Angebot & Abschluss',
    dauer: '15 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Digital signiertes Dokument (DocuSign/PandaDoc) mit Leistungsumfang, Preis, Zahlungsmodalitaeten, Datenschutzhinweis, Stornierungsbedingungen. HubSpot-Deal auf Gewonnen gesetzt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT012',
    source_task_id: 'KP2-12',
    title: 'Willkommens-E-Mail',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.4 Onboarding',
    dauer: '10 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Herzliche Begruessungs-E-Mail direkt nach Auftragsbestaetigung: Vorfreude ausdruecken, naechste Schritte erklaeren, Terminvorschlag fuer Kick-off, Zugangsdaten-Anfrage falls noetig.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT013',
    source_task_id: 'KP2-13',
    title: 'Projekt anlegen',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.4 Onboarding',
    dauer: '15 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Trello-Board aus Template geklont (Spalten: Backlog, In Arbeit, Review, Fertig), Google-Drive-Ordner angelegt (Vertraege, Doku, Kommunikation), HubSpot-Projektlink gesetzt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-VT014',
    source_task_id: 'KP2-14',
    title: 'Kick-off-Termin',
    category: 'Vertrieb & Onboarding',
    subprocess: '2.4 Onboarding',
    dauer: '45 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Strukturiertes Protokoll: Projektziele nochmals bestaetigt, Zeitplan und Meilensteine abgestimmt, Kommunikationskanal festgelegt (E-Mail/Slack), Workshop-Termin fixiert, naechste Aufgaben mit Deadline fuer beide Seiten.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP3: Leistungserbringung ────────────────────────────────
  {
    sop_id: 'SOP-LB001',
    source_task_id: 'KP3-01',
    title: 'Workshop-Vorbereitung',
    category: 'Leistungserbringung',
    subprocess: '3.1 KI-Potenzialanalyse',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Drei Deliverables: (1) Angepasste Workshop-Agenda (Branche, bekannte Probleme), (2) geklontes Miro-Board (4 Spalten: Prozesse/Zeitfresser/Ideen/Priorisierung), (3) Praesentation mit Kundenlogo und 5 branchenspezifischen KI-Beispielen.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB002',
    source_task_id: 'KP3-02',
    title: 'Workshop Teil 1 - Prozessanalyse',
    category: 'Leistungserbringung',
    subprocess: '3.1 KI-Potenzialanalyse',
    dauer: '120 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Dokumentierte Ist-Situation: alle relevanten Geschaeftsprozesse aufgenommen, Zeitfresser und manuelle Taetigkeiten identifiziert und markiert, Systemlandschaft skizziert, Schmerzpunkte priorisiert (vom Kunden selbst bewertet).',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB003',
    source_task_id: 'KP3-03',
    title: 'Workshop Teil 2 - Loesungsfindung',
    category: 'Leistungserbringung',
    subprocess: '3.1 KI-Potenzialanalyse',
    dauer: '120 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Miro-Board mit bewerteten Loesungsoptionen: je Idee Nutzen/Aufwand-Matrix, Top-3 Use Cases mit Sternmarkierung, erste Tool-Empfehlungen, Einschaetzung des Kunden zu Umsetzbarkeit und Akzeptanz.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB004',
    source_task_id: 'KP3-04',
    title: 'Massnahmenplan erstellen',
    category: 'Leistungserbringung',
    subprocess: '3.1 KI-Potenzialanalyse',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Professionelles PDF (KI-generiert, mind. 20% manuell personalisiert): Zusammenfassung der Analyse, Top-3 KI-Potenziale mit Tool-Empfehlung und Nutzen, Umsetzungszeitplan, naechste Schritte. Dateiname: Massnahmenplan_[Kunde]_[Datum].pdf.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB005',
    source_task_id: 'KP3-05',
    title: 'Detailplanung',
    category: 'Leistungserbringung',
    subprocess: '3.2 Implementierung',
    dauer: '60 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Detaillierter Umsetzungsplan in Trello: 7-10 Karten mit Beschreibungen, Checklisten, Faelligkeitsdaten (mit 25% Zeitpuffer), 3 Meilensteine (M1: eingerichtet, M2: getestet, M3: uebergeben). Vom Kunden per E-Mail freigegeben.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB006',
    source_task_id: 'KP3-06',
    title: 'Umsetzung (z.B. E-Mail-Automation)',
    category: 'Leistungserbringung',
    subprocess: '3.2 Implementierung',
    dauer: '4-8 Std',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendig implementierte Loesung: Zapier/Make-Workflow eingerichtet, alle Verbindungen zu Kundensystemen hergestellt, ChatGPT-Prompts integriert und getestet, jede Funktion in Notion dokumentiert, Stunden in Toggl erfasst.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB007',
    source_task_id: 'KP3-07',
    title: 'Interne Tests',
    category: 'Leistungserbringung',
    subprocess: '3.2 Implementierung',
    dauer: '120 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Excel/Notion-Testprotokoll: 10+ Testfaelle (KI-generiert) mit Normalfall, Randfaelle, Fehlerfaelle und Edge Cases. Alle Fehler behoben und nachgetestet. Status: alle Tests bestanden. Abgeheftet in Kundenprojektordner.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB008',
    source_task_id: 'KP3-08',
    title: 'Kunden-Uebergabe & Schulung',
    category: 'Leistungserbringung',
    subprocess: '3.2 Implementierung',
    dauer: '90 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: '60-90-minuetiges Schulungs-Meeting (Zoom oder vor Ort): Live-Demo (15 Min), Kund:in probiert selbst (30 Min), Fragen (15 Min). Handout (2 Seiten, kein Fachjargon) direkt nach Schulung per E-Mail. Support-Kanal und Reaktionszeit kommuniziert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB009',
    source_task_id: 'KP3-09',
    title: 'Abnahme',
    category: 'Leistungserbringung',
    subprocess: '3.2 Implementierung',
    dauer: '30 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'PandaDoc/DocuSign-Protokoll: Projektname, Lieferumfang, Testphasendatum, Schulungsdatum, digitale Unterschrift Kund:in. Automatischer Zapier-Trigger: HubSpot-Deal auf Abgeschlossen, Feedback-Aufgabe angelegt. Archiviert in Google Drive.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB010',
    source_task_id: 'KP3-10',
    title: 'Anforderungsanalyse & Intents definieren',
    category: 'Leistungserbringung',
    subprocess: '3.3 KI-Assistenzsysteme',
    dauer: '60 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendige Liste aller Bot-Intents mit Beispielelusserungen, Abgrenzungen und Entitaeten. Basis fuer Chatbot-Konfiguration.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB011',
    source_task_id: 'KP3-11',
    title: 'Wissensdatenbank aufbauen',
    category: 'Leistungserbringung',
    subprocess: '3.3 KI-Assistenzsysteme',
    dauer: '120 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendig befuellte und indexierte Wissensdatenbank: Dokumente eingepflegt, Kategorien angelegt, Suchfunktion getestet.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB012',
    source_task_id: 'KP3-12',
    title: 'Chatbot / Assistenten konfigurieren',
    category: 'Leistungserbringung',
    subprocess: '3.3 KI-Assistenzsysteme',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendig konfigurierter Bot: System-Prompt, Intents verknuepft, Wissensbasis eingebunden, Eskalationspfade definiert. Im Staging getestet.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB013',
    source_task_id: 'KP3-13',
    title: 'Qualitaetstests & Fehlerfaelle pruefen',
    category: 'Leistungserbringung',
    subprocess: '3.3 KI-Assistenzsysteme',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Excel-Testprotokoll: Normal-, Rand- und Fehlerfaelle, Edge Cases, Datenschutz-Szenarien. Alle Fehler dokumentiert und behoben. Status: freigegeben.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB014',
    source_task_id: 'KP3-14',
    title: 'Rollout, Monitoring & Uebergabe',
    category: 'Leistungserbringung',
    subprocess: '3.3 KI-Assistenzsysteme',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Bot produktiv geschaltet, Monitoring (Anfragen/Tag, Eskalationsrate) eingerichtet, Uebergabedokumentation erstellt, Kundenschulung durchgefuehrt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB015',
    source_task_id: 'KP3-15',
    title: 'Prompt-Bibliothek erstellen',
    category: 'Leistungserbringung',
    subprocess: '3.4 Prompt-/Template-Engineering',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Strukturierte Sammlung von 10-20 getesteten Prompts je Anwendungsfall: System-Prompt, User-Prompt, Beispielausgabe, Qualitaetskriterien. In Notion kategorisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB016',
    source_task_id: 'KP3-16',
    title: 'Qualitaetsregeln & Guardrails definieren',
    category: 'Leistungserbringung',
    subprocess: '3.4 Prompt-/Template-Engineering',
    dauer: '45 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Dokumentierte Qualitaets- und Sicherheitsregeln: verbotene Themen, Ausgabeformate, Datenschutz-Guardrails, Freigabeprozess fuer neue Prompts.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB017',
    source_task_id: 'KP3-17',
    title: 'Dokumentenvorlagen (Templates) entwickeln',
    category: 'Leistungserbringung',
    subprocess: '3.4 Prompt-/Template-Engineering',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: '5-10 einsatzbereite Vorlagen fuer haeufige Dokumente (Angebote, Berichte, E-Mails): im Kundenbranding, KI-befuellbar, mit Platzhaltern. In Google Drive.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB018',
    source_task_id: 'KP3-18',
    title: 'Schulungskonzept & Agenda erstellen',
    category: 'Leistungserbringung',
    subprocess: '3.5 Schulung / Enablement',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Detaillierte Agenda: Lernziele, Zeitplan (Bloecke, Pausen), Methoden (Demo, Ueben, Q&A), Voraussetzungen, Teilnehmerliste. Vom Kunden freigegeben.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB019',
    source_task_id: 'KP3-19',
    title: 'Schulungsunterlagen & Playbook erstellen',
    category: 'Leistungserbringung',
    subprocess: '3.5 Schulung / Enablement',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Drei Deliverables: (1) Praesentation (Folien), (2) Handout (2-4 Seiten, kein Fachjargon), (3) Schritt-fuer-Schritt-Playbook. KI-generiert, mind. 20% personalisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB020',
    source_task_id: 'KP3-20',
    title: 'Schulungsdurchfuehrung & Live-Demo',
    category: 'Leistungserbringung',
    subprocess: '3.5 Schulung / Enablement',
    dauer: '90 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: '90-minuetige Schulung: 30 Min Theorie + 45 Min Live-Demo/Ueben + 15 Min Q&A. Teilnehmerliste unterschrieben. Fragen/Antworten in Notion dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-LB021',
    source_task_id: 'KP3-21',
    title: 'Nachbetreuung & Q&A-Session',
    category: 'Leistungserbringung',
    subprocess: '3.5 Schulung / Enablement',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: '30-minuetige Follow-up-Session 1-2 Wochen nach Schulung: offene Fragen klaeren, Ressourcenliste versenden (Tutorials, Cheat-Sheets, Links). Im CRM dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP4: Abrechnung & Controlling ──────────────────────────
  {
    sop_id: 'SOP-AB001',
    source_task_id: 'KP4-01',
    title: 'Stundenerfassung',
    category: 'Abrechnung & Controlling',
    subprocess: '4.1 Buchfuehrung',
    dauer: '5 Min/Tag',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Lueckenlose Zeiterfassung aller abrechenbaren Taetigkeiten in Toggl: Kundenprojekt korrekt zugeordnet, beschreibender Titel (z.B. KP3-01 Workshop-Vorbereitung Firma XY), Start- und Endzeit. Tages- und Wochenbericht plausibel geprueft.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB002',
    source_task_id: 'KP4-02',
    title: 'Belege sammeln',
    category: 'Abrechnung & Controlling',
    subprocess: '4.1 Buchfuehrung',
    dauer: '10 Min/Woche',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Alle Papierbelege per Lexoffice-App fotografiert (OCR-Erkennung automatisch). Alle digitalen Rechnungen an Lexoffice-E-Mail weitergeleitet. Bank-Sync abgeglichen. Alle Buchungen kategorisiert und ohne offene Posten.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB003',
    source_task_id: 'KP4-03',
    title: 'Rechnungen erstellen',
    category: 'Abrechnung & Controlling',
    subprocess: '4.1 Buchfuehrung',
    dauer: '60 Min/Monat',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Fuer jeden Kunden eine Lexoffice-Rechnung: Stunden aus Toggl-Export als Positionen (Datum, Beschreibung, Stunden, 95 EUR/Std.), Toggl-PDF als Anhang, Zahlungsziel 14 Tage. Starter-Pakete als Vorauszahlung. Alle per Lexoffice-Direktversand.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB004',
    source_task_id: 'KP4-04',
    title: 'Zahlungseingaenge pruefen',
    category: 'Abrechnung & Controlling',
    subprocess: '4.1 Buchfuehrung',
    dauer: '15 Min/Woche',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Woechentlich alle Kontoauszuege mit offenen Rechnungen abgeglichen. Eingegangene Zahlungen in Lexoffice als bezahlt markiert. Ueberfaellige Rechnungen in Mahnliste eingetragen. Liquiditaetsuebersicht aktuell.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB005',
    source_task_id: 'KP4-05',
    title: 'Zahlungserinnerung (7 Tage)',
    category: 'Abrechnung & Controlling',
    subprocess: '4.2 Mahnwesen',
    dauer: '10 Min/Woche',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Automatisierte freundliche E-Mail 7 Tage nach Faelligkeit: Bezug auf Rechnung, Betrag, Zahlungsdetails, Bitte um Rueckmeldung bei Fragen. Kein Vorwurf. CRM-Notiz angelegt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB006',
    source_task_id: 'KP4-06',
    title: 'Erste Mahnung (14 Tage)',
    category: 'Abrechnung & Controlling',
    subprocess: '4.2 Mahnwesen',
    dauer: '5 Min/Fall',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Formelle Mahnung mit Rechnungsnummer, offener Betrag, Mahngebuehr 5 EUR, neue Zahlungsfrist (7 Tage), Hinweis auf weitere Schritte. Per E-Mail und Post. CRM: Stage auf Mahnung 1 gesetzt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-AB007',
    source_task_id: 'KP4-07',
    title: 'Zweite Mahnung & Anruf (21 Tage)',
    category: 'Abrechnung & Controlling',
    subprocess: '4.2 Mahnwesen',
    dauer: '15 Min/Fall',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Zweite Mahnung mit erhoehter Mahngebuehr (10 EUR). Telefonanruf: Was ist passiert? Zahlungsvereinbarung oder letzte Frist? Alles im CRM dokumentiert: Datum, Gespraeche, Ergebnis, naechster Schritt (Zahlung oder Inkasso).',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP5: Kundenbindung & After-Sales ───────────────────────
  {
    sop_id: 'SOP-KB001',
    source_task_id: 'KP5-01',
    title: 'Abschlussgespraech',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.1 Projektabschluss',
    dauer: '30 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Dokumentiertes 30-minuetiges Zoom-Gespraech: besprochene Projekterfolge, Kundenfeedback (direkt notiert), Ausblick auf weiterfuehrende Moeglichkeiten skizziert, Testimonial-Anfrage gestellt (falls Stimmung gut). Protokoll im CRM hinterlegt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB002',
    source_task_id: 'KP5-02',
    title: 'Feedback einholen',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.1 Projektabschluss',
    dauer: '15 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Automatisch via Zapier nach Abnahme versendet. 5 Fragen: Zufriedenheit (1-5), was gefiel besonders, was koennte besser sein, Weiterempfehlung (ja/nein), Zitat-Freigabe (ja/nein). Antworten in Google Sheets. Monatliche Auswertung.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB003',
    source_task_id: 'KP5-03',
    title: 'Testimonial anfragen',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.1 Projektabschluss',
    dauer: '10 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Personalisierte E-Mail mit fertigem 2-3-Saetze-Entwurf (basierend auf Feedback-Antworten, KI-generiert). Kund:in muss nur noch bestaetigen oder leicht anpassen. Erhaltene Testimonials in Notion-Datenbank gespeichert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB004',
    source_task_id: 'KP5-04',
    title: 'After-Sales Follow-up (6 Wochen)',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.1 Projektabschluss',
    dauer: '10 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Kurze E-Mail (max. 3 Saetze) 6 Wochen nach Abnahme: direkter Bezug auf abgeschlossenes Projekt, relevanter Artikel oder Tool-Tipp als Mehrwert, kein Verkaufsdruck. CRM-Aufgabe automatisch via Zapier 42 Tage nach Abnahme.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB005',
    source_task_id: 'KP5-05',
    title: 'Relevante Infos teilen',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.2 Kundenbindung',
    dauer: '5 Min/Fall',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Maximal 3-Saetze-E-Mail wenn relevanter Artikel/Tool fuer spezifischen Kunden gefunden: direkter Bezug auf Kundenbranche oder -projekt, kein Verkauf. Google Alert oder Feedly als Quelle. Max. 1x/Monat je Kunde.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB006',
    source_task_id: 'KP5-06',
    title: 'Quartalscheck Bestandskunden',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.2 Kundenbindung',
    dauer: '15 Min/Kunde',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Kurze E-Mail oder Anruf je Bestandskunde: Wie laeuft die implementierte Loesung? Gibt es neue Herausforderungen? Termin anbieten? CRM-Notiz mit aktuellem Status und naechster Wiedervorlage aktualisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB007',
    source_task_id: 'KP5-07',
    title: 'Geburtstags- und Weihnachtsgruss',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.2 Kundenbindung',
    dauer: '5-10 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Geburtstag: automatisch via CRM-Trigger, personalisierte E-Mail, kein Verkauf. Weihnachten: branchenspezifische KI-generierte Varianten (3 Segmente), als Batch per Mailchimp, ohne Abmeldelink (berechtigtes Interesse).',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-KB008',
    source_task_id: 'KP5-08',
    title: 'Case Study erstellen',
    category: 'Kundenbindung & After-Sales',
    subprocess: '5.1 Projektabschluss',
    dauer: '120 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Drei Laengen einer Case Study: (A) Sehr kurz (2-3 Saetze, fuer Startseite/Kachel), (B) Mittel (ca. 100 Woerter, fuer Leistungsseite), (C) Ausfuehrlich (Ausgangslage, Vorgehen, Ergebnis, Zitat - fuer Case-Study-Seite). Alle in Notion dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── MP: Managementprozesse ──────────────────────────────────
  {
    sop_id: 'SOP-MP001',
    source_task_id: 'MP-01',
    title: 'KPI-Analyse (Quartalscheck)',
    category: 'Managementprozesse',
    subprocess: '1.1 Quartalscheck',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Quartalsweise Auswertung aller Geschaefts-KPIs: Umsatz (Soll/Ist), Neukunden, Conversion-Rate, Website-Besucher, Social-Media-Follower. KI-Analyse der Abweichungen > 20%. Dokumentiert in Google Sheets und Notion.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MP002',
    source_task_id: 'MP-02',
    title: 'SWOT & Quartalsziele',
    category: 'Managementprozesse',
    subprocess: '1.1 Quartalscheck',
    dauer: '45 Min',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Mini-SWOT-Analyse (Staerken, Schwaechen, Chancen, Risiken) fuer das abgelaufene Quartal. Daraus abgeleitet: 1-3 konkrete, messbare Ziele fuer das naechste Quartal (z.B. Conversion-Rate von 30% auf 35% steigern). In Notion dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MP003',
    source_task_id: 'MP-03',
    title: 'Abo-Verwaltung & Kostenoptimierung',
    category: 'Managementprozesse',
    subprocess: '1.2 Finanzen',
    dauer: '15 Min/Monat',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Monatliche Kontrolle aller Software-Abonnements: Gesamtkosten berechnet, ungenutzte Abos identifiziert, Kuendigungen sofort durchgefuehrt, Kontoauszug auf vergessene Abbuchungen geprueft. Liste in Notion aktualisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MP004',
    source_task_id: 'MP-04',
    title: 'Jahresabschluss-Vorbereitung',
    category: 'Managementprozesse',
    subprocess: '1.2 Finanzen',
    dauer: '2 Std/Jahr',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Alle Belege des Jahres vollstaendig in Lexoffice, alle Buchungen kategorisiert, BWA (Betriebswirtschaftliche Auswertung) exportiert, Jahresbericht fuer Steuerberater vorbereitet. Ordner in Google Drive uebergeben.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-MP005',
    source_task_id: 'MP-05',
    title: 'Qualitaetsmanagement-Review',
    category: 'Managementprozesse',
    subprocess: '1.3 Qualitaet',
    dauer: '30 Min/Quartal',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Quartalsweises Qualitaetsreview: Alle Kundenfeedbacks ausgewertet (Durchschnittsnote, Themen-Muster), Prozesse die oft Probleme verursachen identifiziert, neue Vorlagen/Checklisten erstellt oder angepasst. Protokoll in Notion.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── UP: IT & Weiterbildung ──────────────────────────────────
  {
    sop_id: 'SOP-UP001',
    source_task_id: 'UP-01',
    title: 'Monatlicher Software-Update-Check',
    category: 'IT & Weiterbildung',
    subprocess: 'UP1 IT & Tool-Management',
    dauer: '30 Min/Monat',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Alle kritischen Software-Updates installiert: Betriebssystem, Browser, WordPress-Plugins, Sicherheits-Tools. Protokolleintrag in Notion: Datum, was aktualisiert, besondere Vorkommnisse.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP002',
    source_task_id: 'UP-02',
    title: 'Passwort-Hygiene & 2FA-Check',
    category: 'IT & Weiterbildung',
    subprocess: 'UP1 IT & Tool-Management',
    dauer: '15 Min/Monat',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: '1Password/Bitwarden Security-Audit: schwache oder doppelte Passwoerter identifiziert, mind. 1 kritisches Passwort erneuert, 2FA fuer alle wichtigen Accounts (HubSpot, Lexoffice, WordPress, Google) aktiv. Backup-Codes sicher gespeichert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP003',
    source_task_id: 'UP-03',
    title: 'Backup-Pruefung',
    category: 'IT & Weiterbildung',
    subprocess: 'UP1 IT & Tool-Management',
    dauer: '20 Min/Monat',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Monatliche Pruefung: TimeMachine und Backblaze aktuell?, WordPress-Backup (UpdraftPlus) in Google Drive vorhanden? Pflicht: Stichproben-Restore einer beliebigen Datei durchgefuehrt - Datei war wiederherstellbar (Beweis). Datum im Notion-Log.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP004',
    source_task_id: 'UP-04',
    title: 'Abo-Check (monatlich)',
    category: 'IT & Weiterbildung',
    subprocess: 'UP1 IT & Tool-Management',
    dauer: '15 Min/Monat',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Alle Abonnements auf Nutzung geprueft: Dieses Tool diesen Monat wirklich genutzt? Ungenutzte Abos sofort gekuendigt oder downgegradet. Kontoauszug auf vergessene Abbuchungen geprueft. Liste aktualisiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP005',
    source_task_id: 'UP-05',
    title: 'Lern-Slot blocken (einmalig)',
    category: 'IT & Weiterbildung',
    subprocess: 'UP2 Weiterbildung',
    dauer: 'Einmalig',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Einmaliger Setup: woechentlicher Termin Lernzeit - KI & Beratung - NICHT BUCHBAR (z.B. Freitag 9-12 Uhr) als dauerhafte Wiederholung im Google Calendar eingetragen. Mit Calendly synchronisiert - diese Zeit ist nie fuer Kundentermine buchbar.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP006',
    source_task_id: 'UP-06',
    title: 'KI-News-Recherche',
    category: 'IT & Weiterbildung',
    subprocess: 'UP2 Weiterbildung',
    dauer: '90 Min/Woche',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Woechentliche Lerneinheit: neue KI-Tools getestet (Kurztest 15 Min), relevante Blogartikel/Podcasts konsumiert, Erkenntnisse als strukturierte Notiz in Notion. Besonders interessante Faelle als Basis fuer eigene Blogartikel markiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP007',
    source_task_id: 'UP-07',
    title: 'Kurs / Tutorial absolvieren',
    category: 'IT & Weiterbildung',
    subprocess: 'UP2 Weiterbildung',
    dauer: 'Variabel',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Abgeschlossener Online-Kurs oder Tutorial (Udemy, YouTube, LinkedIn Learning): Zertifikat gespeichert (falls vorhanden), 3-5-Punkte-Zusammenfassung der wichtigsten Erkenntnisse in Notion. Direkt anwendbare Learnings als Aufgaben in Trello.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP008',
    source_task_id: 'UP-08',
    title: 'Netzwerk-Event besuchen',
    category: 'IT & Weiterbildung',
    subprocess: 'UP2 Weiterbildung',
    dauer: '2-4 Std',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Neue Kontakte vom Event sofort in HubSpot angelegt: Name, Unternehmen, Gespraeche notiert, Follow-up-Aufgabe gesetzt (personalisierte E-Mail innerhalb 48h). Event-Erkenntnisse in Notion. Nuetzliche Kontakte als potenzielle Kunden oder Partner markiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-UP009',
    source_task_id: 'UP-09',
    title: 'Tool-Dokumentation pflegen',
    category: 'IT & Weiterbildung',
    subprocess: 'UP1 IT & Tool-Management',
    dauer: '15 Min/Woche',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Woechentliche Pflege der internen Tool-Doku: neue Zugaenge eingetragen, Konfigurationsaenderungen dokumentiert, Besonderheiten/Tipps notiert, veraltete Eintraege aktualisiert. Ziel: jeder neue Mitarbeiter kann alle Tools nach Doku bedienen.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP6: IT-Beratung (KP6-04..KP6-09) ─────────────────────
  {
    sop_id: 'SOP-IT004',
    source_task_id: 'KP6-04',
    title: 'Cloud/Hybrid-Architektur planen',
    category: 'IT-Beratung',
    subprocess: '6.2 Architektur & Modernisierung',
    dauer: '120 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Visuelles Architekturdiagramm (draw.io), Migrations-Roadmap mit Phasen, Abhaengigkeiten und Risiken. DSGVO-Anforderungen beruecksichtigt.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT005',
    source_task_id: 'KP6-05',
    title: 'Tool-Auswahl & Systemintegration',
    category: 'IT-Beratung',
    subprocess: '6.2 Architektur & Modernisierung',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Bewertungsmatrix (3 Alternativen x 8 Kriterien), klare Empfehlung mit Begruendung, Integrationskonzept fuer ausgewaehltes Tool.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT006',
    source_task_id: 'KP6-06',
    title: 'Umsetzung & Konfiguration',
    category: 'IT-Beratung',
    subprocess: '6.2 Architektur & Modernisierung',
    dauer: '4-8 Std',
    automation_level: 'manual',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendig eingerichtetes System: alle Konfigurationen vorgenommen, Integrationen getestet, Basisdokumentation erstellt, Stunden in Toggl erfasst.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT007',
    source_task_id: 'KP6-07',
    title: 'Runbook & Betriebshandbuch erstellen',
    category: 'IT-Beratung',
    subprocess: '6.3 Betriebsdokumentation',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Professionelles Betriebshandbuch: Systemuebersicht, Routineaufgaben (tgl./woechentl./monatl.), Troubleshooting-Guide, Notfallkontakte, Eskalationspfade.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT008',
    source_task_id: 'KP6-08',
    title: 'Monitoring & Alerting einrichten',
    category: 'IT-Beratung',
    subprocess: '6.3 Betriebsdokumentation',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Monitoring-Tool konfiguriert: Verfuegbarkeit, Performance, Sicherheitsereignisse ueberwacht. Alerts fuer kritische Ereignisse eingerichtet und getestet.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-IT009',
    source_task_id: 'KP6-09',
    title: 'Uebergabe & Abnahme (IT)',
    category: 'IT-Beratung',
    subprocess: '6.3 Betriebsdokumentation',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Formelles Abnahmeprotokoll: alle Projektziele geprueft, Betriebshandbuch uebergeben, Schulung durchgefuehrt, Kundenzufriedenheit dokumentiert, digital signiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  // ── KP7: Cybersecurity ──────────────────────────────────────
  {
    sop_id: 'SOP-CS001',
    source_task_id: 'KP7-01',
    title: 'Fragebogen & Selbstauskunft',
    category: 'Cybersecurity',
    subprocess: '7.1 Security Quick-Check',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Standardisierter Fragebogen (DIN SPEC 27076 angelehnt): 30 Fragen zu Zugriffsschutz, E-Mail, Backup, Updates, Netzwerk. Mit KI-Erstbewertung.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS002',
    source_task_id: 'KP7-02',
    title: 'Risiko- & Schwachstellenbewertung',
    category: 'Cybersecurity',
    subprocess: '7.1 Security Quick-Check',
    dauer: '90 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Risiko-Heatmap: Top-10 Sicherheitsrisiken nach Eintrittswahrscheinlichkeit x Schadenspotenzial bewertet, DSGVO-relevante Risiken markiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS003',
    source_task_id: 'KP7-03',
    title: 'Massnahmenplan & Security-Roadmap',
    category: 'Cybersecurity',
    subprocess: '7.1 Security Quick-Check',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Strukturierter Massnahmenplan: Sofortmassnahmen (7 Tage), kurzfristig (30 Tage), mittelfristig (90 Tage). Mit Aufwandschaetzung und Verantwortlichkeiten.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS004',
    source_task_id: 'KP7-04',
    title: 'Identitaeten & Zugriffsrechte (MFA, Rollen)',
    category: 'Cybersecurity',
    subprocess: '7.2 Hardening & Baseline',
    dauer: '120 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Dokumentiertes Berechtigungskonzept: alle Nutzer mit Rollen, Need-to-Know-Prinzip umgesetzt, MFA fuer kritische Accounts aktiviert und dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS005',
    source_task_id: 'KP7-05',
    title: 'E-Mail-Schutz (SPF/DKIM/DMARC) einrichten',
    category: 'Cybersecurity',
    subprocess: '7.2 Hardening & Baseline',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'SPF, DKIM und DMARC fuer die Kundendomain konfiguriert, mit Online-Tools (MXToolbox) verifiziert, Ergebnisse dokumentiert, Kunden informiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS006',
    source_task_id: 'KP7-06',
    title: 'Endpoint-Haertung & Patch-Management',
    category: 'Cybersecurity',
    subprocess: '7.2 Hardening & Baseline',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Haertungs-Checkliste abgearbeitet: Firewall aktiv, automatische Updates aktiviert, AV installiert, Festplattenverschluesselung aktiv, alles dokumentiert.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS007',
    source_task_id: 'KP7-07',
    title: 'Backup-Strategie entwickeln (3-2-1-Regel)',
    category: 'Cybersecurity',
    subprocess: '7.3 Backup & Recovery',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Dokumentiertes Backup-Konzept: 3 Kopien, 2 Medien, 1 extern. Automatisierte Backup-Jobs konfiguriert, Aufbewahrungsfristen definiert, DSGVO-konform.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS008',
    source_task_id: 'KP7-08',
    title: 'Restore-Test durchfuehren & dokumentieren',
    category: 'Cybersecurity',
    subprocess: '7.3 Backup & Recovery',
    dauer: '90 Min',
    automation_level: 'semi',
    maturity_level: 3,
    output_beschreibung: 'Dokumentierter Restore-Test: Datum, getestetes System, wiederhergestellte Datenmenge, Dauer des Restores, Ergebnis (erfolgreich/fehlgeschlagen), Unterschrift.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS009',
    source_task_id: 'KP7-09',
    title: 'Awareness-Training konzipieren',
    category: 'Cybersecurity',
    subprocess: '7.4 Awareness & Schulung',
    dauer: '45 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Massgeschneidertes Schulungskonzept: Themen (Phishing, Passwoerter, Social Engineering), Methoden, Zeitplan, branchenspezifische Beispiele.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS010',
    source_task_id: 'KP7-10',
    title: 'Phishing-Simulation durchfuehren',
    category: 'Cybersecurity',
    subprocess: '7.4 Awareness & Schulung',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Ergebnisbericht der Simulation: Klickrate, Melderate, Abteilungsvergleich (anonymisiert). Empfehlungen fuer Nachschulungsbedarf.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS011',
    source_task_id: 'KP7-11',
    title: 'Security-Richtlinien erstellen',
    category: 'Cybersecurity',
    subprocess: '7.4 Awareness & Schulung',
    dauer: '60 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Einfache, verstaendliche Sicherheitsrichtlinie (max. 5 Seiten): Passwortregeln, Geraetenutzung, Meldepflichten, Internet/E-Mail-Nutzung. Von Mitarbeitern unterschrieben.',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS012',
    source_task_id: 'KP7-12',
    title: 'Notfall-Playbook erstellen',
    category: 'Cybersecurity',
    subprocess: '7.5 Incident Response',
    dauer: '90 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Vollstaendiges IR-Playbook: Eskalationspfade, Kontaktlisten, konkrete Handlungsanweisungen fuer Top-4-Szenarien (Ransomware, Datenpanne, Phishing, Kontouebernahme).',
    produces_deliverable: null,
    status: 'approved',
  },
  {
    sop_id: 'SOP-CS013',
    source_task_id: 'KP7-13',
    title: 'Meldewege & Notfallkontakte definieren',
    category: 'Cybersecurity',
    subprocess: '7.5 Incident Response',
    dauer: '30 Min',
    automation_level: 'full',
    maturity_level: 3,
    output_beschreibung: 'Laminierte Notfallkarte: BSI, Datenschutzbehoerde, IT-Dienstleister, interne Kontakte. Meldewege-Poster fuer Buero. Alle Kontakte aktuell verifiziert.',
    produces_deliverable: null,
    status: 'approved',
  },
]

// All SOPs combined
const SOPS: SopEntry[] = [...GENERAL_SOPS, ...OPERATIVE_SOPS]

export async function seedSopCatalog(_tenantId: string) {
  logger.info('Seeding SOP Catalog...', { module: MOD })

  // 1. Deliverable-Lookup-Map aufbauen
  const allDeliverables = await db
    .select({ id: deliverables.id, name: deliverables.name })
    .from(deliverables)
    

  const deliverableByName = new Map(allDeliverables.map(d => [d.name, d.id]))
  logger.info(`${allDeliverables.length} Deliverables geladen fuer Lookup`, { module: MOD })

  let created = 0
  let skipped = 0
  let warnCount = 0

  for (const sop of SOPS) {
    // 2. Idempotenz pruefen (zweistufig)
    if (sop.source_task_id) {
      const [existing] = await db
        .select({ id: sopDocuments.id })
        .from(sopDocuments)
        .where(
          and(eq(sopDocuments.sourceTaskId, sop.source_task_id),
            isNull(sopDocuments.deletedAt)))
      if (existing) {
        skipped++
        continue
      }
    } else {
      const [existing] = await db
        .select({ id: sopDocuments.id })
        .from(sopDocuments)
        .where(
          and(eq(sopDocuments.title, sop.title),
            isNull(sopDocuments.deletedAt)))
      if (existing) {
        skipped++
        continue
      }
    }

    // 3. Deliverable-Verknuepfung aufloesen
    let producesDeliverableId: string | null = null
    if (sop.produces_deliverable) {
      const delivName = DELIVERABLE_CODE_TO_NAME[sop.produces_deliverable] ?? null
      if (delivName) {
        producesDeliverableId = deliverableByName.get(delivName) ?? null
        if (!producesDeliverableId) {
          logger.warn(`Deliverable nicht gefunden: ${sop.produces_deliverable} -> ${delivName}`, { module: MOD })
          warnCount++
        }
      } else {
        logger.warn(`Kein Deliverable-Name fuer Code: ${sop.produces_deliverable} (SOP: ${sop.sop_id})`, { module: MOD })
        warnCount++
      }
    }

    // 4. SOP direkt einfuegen (db.insert, NICHT SopService.create)
    await db.insert(sopDocuments).values({
      title: sop.title,
      category: sop.category,
      status: sop.status ?? 'draft',
      version: '1.0.0',
      automationLevel: sop.automation_level ?? null,
      aiCapable: sop.automation_level !== 'manual',
      maturityLevel: sop.maturity_level ?? null,
      estimatedDurationMinutes: parseDauer(sop.dauer),
      subprocess: sop.subprocess ?? null,
      sourceTaskId: sop.source_task_id ?? null,
      producesDeliverableId,
      purpose: sop.output_beschreibung ?? null,
      scope: null,
      tools: [],
      tags: [],
    })
    created++
  }

  logger.info(
    `SOP Catalog seeded: ${created} erstellt, ${skipped} bereits vorhanden, ${warnCount} Deliverable-Lookup-Warnungen`,
    { module: MOD })
}
